# Generated by Django 6.0.2 on 2026-03-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultitem',
            name='encrypted_content',
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='encrypted_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='encrypted_password',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='encrypted_username',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='VaultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vault_files/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vault_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='vault.vaultitem')),
            ],
        ),
    ]
